config/routes.rb
Hookupify::Application.routes.draw do

  resources :comments

  resources :badges

  resources :votes

  resources :tags

  resources :users
  resource :account, :controller => :users
  resource :user_session

  resources :questions do
    resources :answers
    resources :comments
    collection do
      get 'tags'
    end
  end
  resources :answers

  resources :question_votes

   root :controller => :questions, :action => :index

end

app/models/question.rb
class Question < ActiveRecord::Base
  acts_as_taggable_on :tags

  belongs_to :user
  has_many :answers
  has_many :votes, :as => :voteable
  has_many :comments

  scope :sorted_by, lambda {|sort|
    if sort == "newest"
      order("created_at DESC")
    elsif sort == "votes"
      order("score DESC");
    elsif sort == "active"
      order("active_at DESC");
    elsif sort == "views"
      order("views DESC");
    end
  }

  scope :title_like, lambda {|title|
    where("questions.title LIKE ?",  "%" + title + "%")
  }

  scope :answered, lambda {|answered|
    if(answered.to_i == 1)
      joins("join answers on answers.question_id = questions.id").
      group("questions.id").
      where("answers.score > 0")
    else
      where("questions.id NOT IN (?)", Question.answered(1).map(&:id))
    end
  }

  scope :user_id_equals, lambda { |id|
    where(:user_id => id)
  }

  def excerpt
    if text 
      exc = text[0, 190]
      if exc != text
        exc += " ..."
      end
      return exc
    else
      return ""
    end
  end

  def up_votes
    Vote.count :all, :conditions => {:post_id => self.id, :value => 1, :type => :question}
  end

  def down_votes
    QuestionVote.count :all, :conditions => {:post_id => self.id, :value => -1, :type => :question}
  end

  def num_answers
    answers.count
  end

  def answered?
    Answer.count(:all, :conditions => ["question_id = ? AND score > 0", id]) > 0
  end

  def update_active_at
    self.active_at = Time.now
  end

  def self.filter(list_options)
    raise(ArgumentError, "Expected Hash, got #{list_options.inspect}") unless list_options.is_a?(Hash)
    ar_proxy = self
    list_options.each do |key, value|
      key = key.to_sym
      next unless self.list_option_names.include?(key)
      next if value.blank?
      puts "sending #{key} with #{value}"
      ar_proxy = ar_proxy.send(key, value)
    end
    ar_proxy.all()
  end

  def self.list_option_names
      self.scopes.map{|s| s.first}.push :tagged_with 
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml
  before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]

  def index
    params[:sorted_by] ||= "newest"
    @sorted_by = params[:sorted_by]

    @questions = Question.filter(params);

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
    verify_user(@question)
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    @question.update_active_at

    respond_to do |format|
      if @question.save
        format.html { redirect_to(question_answers_path(@question), :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])
    verify_user(@question)
    @question.update_active_at

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(question_answers_path(@question), :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    verify_user(@question)

    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end

  def tags
    @tags = Question.tag_counts_on(:tags)
  end

  private
  
  def verify_user(question)
    unless current_user == question.user
      flash[:notice] = "You must be the creator of this question to edit it"
      redirect_to :action => :show
      return false
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label 'Tags (comma delimited; i.e. "programming, ruby, rails")' %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="subheader">
  <h1>Listing questions</h1> 
  <div class="subheader-search">
    <%= form_tag({:action => 'index'}, :method => :get) do %>
      Search Questions: <%= text_field_tag :title_like %>
    <% end %>
  </div>
  <div id="tabs">
    <% ["newest", "votes", "active", "views"].each do |sort| %>
      <%= link_to sort.capitalize, merge_params(:action => :index, :sorted_by => sort), :class => @sorted_by==sort ? "youarehere" : "" %>
    <% end %>
  </div>

</div>

<div>
  <% @questions.each do |question| %>
    <%= render_cell :question, :summary, :question => question, :excerpt => true %>
  <% end %>
</div>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
  <script type="text/javascript">
    $(document).ready(function() {
      votes = <%= @question.votes %>
      $("span.vote-count-post").html(votes);

        $("div.upvote-off").live('click', function() {
          $.post("<%= question_votes_path %>", { question_id: "<%= @question.id %>", vote: "up" } ); 
          if ( $("div#upvote").hasClass('upvote-off') ) {
            votes += 1;
          }
          if ( $("div#downvote").hasClass("downvote-on") ) {
            votes += 1;
          }

          $("div#upvote").addClass('upvote-on');
          $("div#upvote").removeClass('upvote-off');
          $("div#downvote").removeClass('downvote-on');
          $("div#downvote").addClass('downvote-off');

          $("span.vote-count-post").text(votes);

        });

      $("div.downvote-off").live('click', function() {
          $.post("<%= question_votes_path %>", { question_id: "<%= @question.id %>", vote: "down" } ); 
          if ( $("div#downvote").hasClass('downvote-off') ) {
            votes -= 1;
          }
          if ( $("div#upvote").hasClass("upvote-on") ){
            votes -= 1;
          }

          $("div#downvote").addClass('downvote-on');
          $("div#downvote").removeClass('downvote-off');
          $("div#upvote").removeClass('upvote-on');
          $("div#upvote").addClass('upvote-off');

          $("span.vote-count-post").text(votes);
      });
    <% end %>
  });
 
  </script>

<div class="subheader">
  <h1><%= @question.title %></h1>
</div>

<p id="notice"><%= notice %></p>

<table>
  <tbody>
    <tr>
      <td class="votecell">
        <div class="vote">
          <div class="votearrow <%= upvoted_question?(current_user, @question) ? 'upvote-on' : 'upvote-off' %>" id="upvote"></div>
          <span class="vote-count-post"> </span>
          <div class="votearrow <%= downvoted_question?(current_user, @question) ? 'downvote-on' : 'downvote-off' %>" id="downvote"></div>
        </div>
      </td>
      <td class="postcell">
        <div class="post-text">
          <%= @question.text %>
        </div>
      </td>
    </tr>
  </tbody>
</table>
<div class="started fr">
  <div class="user-action-time">asked <span class="relativetime"> <%= time_ago_in_words(@question.created_at) %> ago</span></div>
  <div class="user-details">
    by <%= link_to @question.user.login, @question.user %>
  </div>
</div>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Answer this question', new_question_answer_path(@question) %>

app/views/questions/tags.html.erb
<div class="subheader">
  <h1> Tags </h1>
</div>
<% @tags.each do |tag| %>
  <div style="display:inline; padding-left: 15px; padding-right: 15px"> <%= link_to tag.name, {:controller => :questions, :action => :index, :tagged_with => tag.name}, :class => 'post-tag' %>x<%= tag.count %></div>
<% end %>

<div class="subheader">
  <h1> Tag Cloud </h1>
</div>

<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, { :controller  => :questions, :action => :index, :tagged_with => tag.name }, :class => css_class %>
<% end %>