config/routes.rb
Hookupify::Application.routes.draw do

  resources :comments

  resources :badges

  resources :votes

  resources :tags

  resources :users
  resource :account, :controller => :users
  resource :user_session

  resources :questions do
    resources :answers
    resources :comments
    collection do
      get 'tags'
    end
  end
  resources :answers

  resources :question_votes

   root :controller => :questions, :action => :index

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes, :as => :voteable

  validates_presence_of :question, :user
  
  before_save :update_question_active_at

  def update_question_active_at
    question.update_active_at
    question.save!
  end

  def self.find_all_by_question_id(question_id)
    self.find(:all, :conditions => {:question_id => question_id})
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.xml
  before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :get_question, :only => [:new, :create, :edit, :update, :show, :destroy, :index]

  def index
    @question.views += 1
    @question.save
    if params[:question_id]
      @answers = Answer.find_all_by_question_id params[:question_id]
    else
      @answers = Answer.all
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /answers/1
  # GET /answers/1.xml
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /answers/new
  # GET /answers/new.xml
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
    verify_user(@answer)
  end

  # POST /answers
  # POST /answers.xml
  def create
    @answer = Answer.new(params[:answer])
    @answer.user = current_user
    @answer.question = @question

    verify_user(@answer)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to(question_answers_url(@question), :notice => 'Answer was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.xml
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to([@question, @answer], :notice => 'Answer was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.xml
  def destroy
    @answer = Answer.find(params[:id])

    verify_user(@answer)
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to(question_answers_url(@question)) }
    end
  end

  private

  def verify_user(answer)
    unless current_user == answer.user
      flash[:notice] = "You must be the creator of this answer to edit it"
      redirect_to :action => :show
      return
    end
  end

  def get_question
    @question = Question.find params[:question_id]
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/_question_info.html.erb
<p>
  <b>Question Title:</b>
  <%= @question.title %>
</p>

</p>
  <b>Question Posted by:</b>
  <%= @question.user.login %>
</p>

<p>
  <b>Question text:</b>
  <%= @question.text %>
</p>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', [@question, @answer] %> |
<%= link_to 'Back', question_answers_path(@question) %>

app/views/answers/index.html.erb
<script type="text/javascript">
  function vote(value, obj_type, id, click_obj) {
    container = click_obj.parent();

    $.post("<%= votes_path %>", { vote: {value: value, voteable_type: obj_type, voteable_id: id} }, function(data) {
      if(data.success) {
        container.children(".upvote").toggleClass("upvote-on", data.upvote);
        container.children(".upvote").toggleClass("upvote-off", ! data.upvote);
        container.children(".downvote").toggleClass("downvote-on", data.downvote);
        container.children(".downvote").toggleClass("downvote-off", ! data.downvote);
        container.children(".vote-count-post").text(data.score)
      }
      else {
        str = ""
        for (var key in data.error) {
          str += data.error[key] + "\n";
        }
        alert(str);
      }
    }, "json");
  }

</script>

<div class="subheader">
  <h1><%= @question.title %></h1>
</div>

<p id="notice"><%= notice %></p>

<table>
  <tbody>
    <tr>
      <td class="votecell">
        <div class="vote">
          <div class="upvote votearrow <%= voted?(@question, 1) ? 'upvote-on' : 'upvote-off' %>", onclick="vote(1, 'Question', <%= @question.id %>, $(this))"></div>
          <span class="vote-count-post"> <%= @question.score %> </span>
          <div class="downvote votearrow <%= voted?(@question, -1) ? 'downvote-on' : 'downvote-off' %>", onclick="vote(-1, 'Question', <%= @question.id %>, $(this))"></div>
        </div>
      </td>
      <td class="postcell">
        <div class="post-text">
          <%= @question.text %>
        </div>
      </td>
    </tr>
  </tbody>
</table>
<div class="started fr">
  <div class="user-action-time">asked <span class="relativetime"> <%= time_ago_in_words(@question.created_at) %> ago</span></div>
  <div class="user-details">
    by <%= link_to @question.user.login, @question.user %>
  </div>
</div>

<% if @question.user == current_user %>
  <%= link_to 'Edit this question', edit_question_path(@question) %> |
<% end %>

<%= link_to 'Answer this question', new_question_answer_path(@question) %> | <%= link_to 'Comment on this question', new_question_comment_path(@question) %>

<% if @question.comments.length > 0 %>
  <div class="subheader">
    <h1> Comments </h1>
  </div>
  <% @question.comments.each do |comment| %>
    <table>
      <tbody>
        <td class="postcell">
          <div class="post-text">
            <%= comment.text %> 
          </div>
        </td>
      </tbody>
    </table>
    <div class="started fr">
      <div class="user-action-time">posted <span class="relativetime"> <%= time_ago_in_words(comment.created_at) %> ago</span></div>
      <div class="user-details">
        by <%= link_to comment.user.login, comment.user %>
      </div>
    </div>
<% end %>
<% end %>

<% if @answers.length > 0 %>
  <div class="subheader">
    <h1>Answers</h1>
  </div>

  <% @answers.each do |answer| %>
    <table>
      <tbody>
        <tr>
          <td class="votecell">
            <div class="vote">
              <div class="upvote votearrow <%= voted?(answer, 1) ? 'upvote-on' : 'upvote-off' %>", onclick="vote(1, 'Answer', <%= answer.id %>, $(this))"></div>
              <span class="vote-count-post"> <%= answer.score %> </span>
              <div class="downvote votearrow <%= voted?(answer, -1) ? 'downvote-on' : 'downvote-off' %>", onclick="vote(-1, 'Answer', <%= answer.id %>, $(this))"></div>
            </div>
          </td>
          <td class="postcell">
            <div class="post-text">
              <%= answer.text %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="started fr">
      <div class="user-action-time">posted <span class="relativetime"> <%= time_ago_in_words(answer.created_at) %> ago</span></div>
      <div class="user-details">
        by <%= link_to answer.user.login, answer.user %>
      </div>
    </div>
    <% if current_user == answer.user %>
      <%= link_to "Edit this answer", edit_question_answer_path(answer.question, answer) %>
    <% end %>
  <% end %>
<% end %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'question_info' %>

<p>
  <b>Answer posted by:</b>
  <%= @answer.user.login %>
</p>

<p>
  <b>Answer Text:</b>
  <%= @answer.text %>
</p>


<%= link_to 'Edit', edit_question_answer_path(@question, @answer) %> |
<%= link_to 'Back', question_answers_path(@question) %>