config/routes.rb
Hookupify::Application.routes.draw do

  resources :comments

  resources :badges

  resources :votes

  resources :tags

  resources :users
  resource :account, :controller => :users
  resource :user_session

  resources :questions do
    resources :answers
    resources :comments
    collection do
      get 'tags'
    end
  end
  resources :answers

  resources :question_votes

   root :controller => :questions, :action => :index

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hookupify</title>
  <%= stylesheet_link_tag 'application.css' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div class="userbar">
    <% if current_user %>
      Welcome, <%= link_to current_user.login, current_user %> (<%= link_to "Edit profile", edit_account_path %>, <%= link_to "Logout", user_session_path, :method => :delete, :confirm => "Are you sure you want to logout?" %>)
    <% else %>
      <%= link_to "Register", new_user_path %> | <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
  <br/>

  <div id="content">
    <div class="nav mainnavs">
        <ul>
            <li><a id="nav-questions" href="/questions">Questions</a></li>
            <li><%= link_to "Tags", tags_questions_path %></li>
            <li><%= link_to "Badges", badges_path  %></li>
            <li><%= link_to "Answered", merge_params(:action => :index, :controller => :questions, :answered => 1)  %></li>
            <li><%= link_to "Unanswered", merge_params(:action => :index, :controller => :questions, :answered => 0)  %></li>
        </ul>
    </div>

    <% if current_user %>
      <div class="nav askquestion">
        <ul>
          <li>
            <%= link_to "Ask question", new_question_path %>
          </li>
        </ul>
      </div>
    <% end %>

    <div class="fc">
      <%= yield %>
    </div>
  </div>

</body>
</html>